"""Add bitacora

Revision ID: 49340e547c4a
Revises: 
Create Date: 2026-04-25 15:45:18.132869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49340e547c4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
